apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service-hornets
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - asian-giant-hornet.com
      secretName: tls-secret
  rules:
    - host: asian-giant-hornet.com
      http:
       paths:
        - path: /hello
          backend:
            serviceName: hornets-service
            servicePort: 5000
        - path: /predict
          backend:
            serviceName: hornets-service
            servicePort: 5000
        - path: /
          backend:
            serviceName: hornets-client-service
            servicePort: 3000
